# Generated by Django 5.0.1 on 2024-04-29 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lampi', '0003_lampi_association_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampi',
            name='device_id',
            field=models.CharField(
                db_index=True, max_length=12, primary_key=True, serialize=False),
        ),
    ]
